"""empty message

Revision ID: 50cc623064f9
Revises: de501b7cf01e
Create Date: 2026-01-09 00:41:27.676702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '50cc623064f9'
down_revision: Union[str, Sequence[str], None] = 'de501b7cf01e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches_gp_extra', sa.Column('nextUpdateTime', sa.Integer(), nullable=False))
    op.drop_column('matches_gp_extra', 'updateTime')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches_gp_extra', sa.Column('updateTime', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('matches_gp_extra', 'nextUpdateTime')
    # ### end Alembic commands ###
