"""empty message

Revision ID: a13f11ab1c0e
Revises: 
Create Date: 2026-01-08 22:14:21.830307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a13f11ab1c0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches_gp_extra', 'team1Legacy',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('matches_gp_extra', 'team2Legacy',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches_gp_extra', 'team2Legacy',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('matches_gp_extra', 'team1Legacy',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
