"""empty message

Revision ID: bc030c886a06
Revises: 
Create Date: 2026-01-10 15:55:43.491219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc030c886a06'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_mem',
    sa.Column('gid', sa.String(length=20), nullable=False),
    sa.Column('mem', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('gid')
    )
    op.create_table('auth_sessions',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=True),
    sa.Column('group_id', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_auth_sessions_code'), 'auth_sessions', ['code'], unique=False)
    op.create_table('fudu_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=50), nullable=False),
    sa.Column('timeStamp', sa.Integer(), nullable=False),
    sa.Column('point', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goods_info',
    sa.Column('marketHashName', sa.String(length=500), nullable=False),
    sa.Column('timeStamp', sa.Integer(), nullable=False),
    sa.Column('goodId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('buffSellPrice', sa.Integer(), nullable=False),
    sa.Column('buffSellNum', sa.Integer(), nullable=False),
    sa.Column('yyypSellPrice', sa.Integer(), nullable=False),
    sa.Column('yyypSellNum', sa.Integer(), nullable=False),
    sa.Column('steamSellPrice', sa.Integer(), nullable=False),
    sa.Column('steamSellNum', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('marketHashName', 'timeStamp')
    )
    op.create_table('group_members',
    sa.Column('gid', sa.String(length=20), nullable=False),
    sa.Column('uid', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('gid', 'uid')
    )
    op.create_table('groupmsg',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('sid', sa.String(length=50), nullable=False),
    sa.Column('timeStamp', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('img_cache_info',
    sa.Column('hash', sa.String(length=255), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_table('live_status',
    sa.Column('liveid', sa.String(length=50), nullable=False),
    sa.Column('islive', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('liveid')
    )
    op.create_table('local_storage',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('val', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('major_hw',
    sa.Column('uid', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('teams', sa.Text(), nullable=False),
    sa.Column('winrate', sa.Float(), nullable=False),
    sa.Column('expval', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('uid', 'stage')
    )
    op.create_table('matches',
    sa.Column('mid', sa.String(length=50), nullable=False),
    sa.Column('steamid', sa.String(length=20), nullable=False),
    sa.Column('seasonId', sa.String(length=20), nullable=False),
    sa.Column('mapName', sa.String(length=50), nullable=False),
    sa.Column('team', sa.Integer(), nullable=False),
    sa.Column('winTeam', sa.Integer(), nullable=False),
    sa.Column('score1', sa.Integer(), nullable=False),
    sa.Column('score2', sa.Integer(), nullable=False),
    sa.Column('pwRating', sa.Float(), nullable=False),
    sa.Column('we', sa.Float(), nullable=False),
    sa.Column('timeStamp', sa.Integer(), nullable=False),
    sa.Column('kill', sa.Integer(), nullable=False),
    sa.Column('death', sa.Integer(), nullable=False),
    sa.Column('assist', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=100), nullable=False),
    sa.Column('pvpScore', sa.Integer(), nullable=False),
    sa.Column('pvpStars', sa.Integer(), nullable=False),
    sa.Column('pvpScoreChange', sa.Integer(), nullable=False),
    sa.Column('pvpMvp', sa.Integer(), nullable=False),
    sa.Column('isgroup', sa.Integer(), nullable=False),
    sa.Column('greenMatch', sa.Integer(), nullable=False),
    sa.Column('entryKill', sa.Integer(), nullable=False),
    sa.Column('headShot', sa.Integer(), nullable=False),
    sa.Column('headShotRatio', sa.Float(), nullable=False),
    sa.Column('flashTeammate', sa.Integer(), nullable=False),
    sa.Column('flashSuccess', sa.Integer(), nullable=False),
    sa.Column('twoKill', sa.Integer(), nullable=False),
    sa.Column('threeKill', sa.Integer(), nullable=False),
    sa.Column('fourKill', sa.Integer(), nullable=False),
    sa.Column('fiveKill', sa.Integer(), nullable=False),
    sa.Column('vs1', sa.Integer(), nullable=False),
    sa.Column('vs2', sa.Integer(), nullable=False),
    sa.Column('vs3', sa.Integer(), nullable=False),
    sa.Column('vs4', sa.Integer(), nullable=False),
    sa.Column('vs5', sa.Integer(), nullable=False),
    sa.Column('dmgArmor', sa.Integer(), nullable=False),
    sa.Column('dmgHealth', sa.Integer(), nullable=False),
    sa.Column('adpr', sa.Float(), nullable=False),
    sa.Column('rws', sa.Float(), nullable=False),
    sa.Column('teamId', sa.BigInteger(), nullable=False),
    sa.Column('throwsCnt', sa.Integer(), nullable=False),
    sa.Column('snipeNum', sa.Integer(), nullable=False),
    sa.Column('firstDeath', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('mid', 'steamid')
    )
    op.create_table('matches_extra',
    sa.Column('mid', sa.String(length=50), nullable=False),
    sa.Column('team1Legacy', sa.Float(), nullable=False),
    sa.Column('team2Legacy', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('mid')
    )
    op.create_table('matches_gp',
    sa.Column('mid', sa.String(length=50), nullable=False),
    sa.Column('steamid', sa.String(length=20), nullable=False),
    sa.Column('mapName', sa.String(length=50), nullable=False),
    sa.Column('team', sa.Integer(), nullable=False),
    sa.Column('winTeam', sa.Integer(), nullable=False),
    sa.Column('score1', sa.Integer(), nullable=False),
    sa.Column('score2', sa.Integer(), nullable=False),
    sa.Column('timeStamp', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('kill', sa.Integer(), nullable=False),
    sa.Column('handGunKill', sa.Integer(), nullable=False),
    sa.Column('entryKill', sa.Integer(), nullable=False),
    sa.Column('awpKill', sa.Integer(), nullable=False),
    sa.Column('death', sa.Integer(), nullable=False),
    sa.Column('entryDeath', sa.Integer(), nullable=False),
    sa.Column('assist', sa.Integer(), nullable=False),
    sa.Column('headShot', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('itemThrow', sa.Integer(), nullable=False),
    sa.Column('flash', sa.Integer(), nullable=False),
    sa.Column('flashTeammate', sa.Integer(), nullable=False),
    sa.Column('flashSuccess', sa.Integer(), nullable=False),
    sa.Column('twoKill', sa.Integer(), nullable=False),
    sa.Column('threeKill', sa.Integer(), nullable=False),
    sa.Column('fourKill', sa.Integer(), nullable=False),
    sa.Column('fiveKill', sa.Integer(), nullable=False),
    sa.Column('vs1', sa.Integer(), nullable=False),
    sa.Column('vs2', sa.Integer(), nullable=False),
    sa.Column('vs3', sa.Integer(), nullable=False),
    sa.Column('vs4', sa.Integer(), nullable=False),
    sa.Column('vs5', sa.Integer(), nullable=False),
    sa.Column('adpr', sa.Float(), nullable=False),
    sa.Column('rws', sa.Float(), nullable=False),
    sa.Column('kast', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('throwsCnt', sa.Integer(), nullable=False),
    sa.Column('bombPlanted', sa.Integer(), nullable=False),
    sa.Column('bombDefused', sa.Integer(), nullable=False),
    sa.Column('smokeThrows', sa.Integer(), nullable=False),
    sa.Column('grenadeDamage', sa.Integer(), nullable=False),
    sa.Column('infernoDamage', sa.Integer(), nullable=False),
    sa.Column('mvp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('mid', 'steamid')
    )
    op.create_table('matches_gp_extra',
    sa.Column('mid', sa.String(length=50), nullable=False),
    sa.Column('team1Legacy', sa.Float(), nullable=True),
    sa.Column('team2Legacy', sa.Float(), nullable=True),
    sa.Column('nextUpdateTime', sa.Integer(), nullable=False),
    sa.Column('fetchCount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('mid')
    )
    op.create_table('member_goods',
    sa.Column('uid', sa.String(length=20), nullable=False),
    sa.Column('marketHashName', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('uid', 'marketHashName')
    )
    op.create_table('members_steamid',
    sa.Column('uid', sa.String(length=20), nullable=False),
    sa.Column('steamid', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('steam_detail_info',
    sa.Column('steamid', sa.String(length=20), nullable=False),
    sa.Column('seasonId', sa.String(length=20), nullable=False),
    sa.Column('pvpScore', sa.Integer(), nullable=False),
    sa.Column('pvpStars', sa.Integer(), nullable=False),
    sa.Column('cnt', sa.Integer(), nullable=False),
    sa.Column('winRate', sa.Float(), nullable=False),
    sa.Column('pwRating', sa.Float(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('rws', sa.Float(), nullable=False),
    sa.Column('pwRatingTAvg', sa.Float(), nullable=False),
    sa.Column('pwRatingCtAvg', sa.Float(), nullable=False),
    sa.Column('kastPerRound', sa.Float(), nullable=False),
    sa.Column('firePowerScore', sa.Integer(), nullable=False),
    sa.Column('killsPerRound', sa.Float(), nullable=False),
    sa.Column('killsPerWinRound', sa.Float(), nullable=False),
    sa.Column('damagePerRound', sa.Float(), nullable=False),
    sa.Column('damagePerRoundWin', sa.Float(), nullable=False),
    sa.Column('roundsWithAKill', sa.Float(), nullable=False),
    sa.Column('multiKillRoundsPercentage', sa.Float(), nullable=False),
    sa.Column('we', sa.Float(), nullable=False),
    sa.Column('pistolRoundRating', sa.Float(), nullable=False),
    sa.Column('marksmanshipScore', sa.Integer(), nullable=False),
    sa.Column('headshotRate', sa.Float(), nullable=False),
    sa.Column('killTime', sa.Integer(), nullable=False),
    sa.Column('smHitRate', sa.Float(), nullable=False),
    sa.Column('reactionTime', sa.Float(), nullable=False),
    sa.Column('rapidStopRate', sa.Float(), nullable=False),
    sa.Column('followUpShotScore', sa.Integer(), nullable=False),
    sa.Column('savedTeammatePerRound', sa.Float(), nullable=False),
    sa.Column('tradeKillsPerRound', sa.Float(), nullable=False),
    sa.Column('tradeKillsPercentage', sa.Float(), nullable=False),
    sa.Column('assistKillsPercentage', sa.Float(), nullable=False),
    sa.Column('damagePerKill', sa.Float(), nullable=False),
    sa.Column('firstScore', sa.Integer(), nullable=False),
    sa.Column('firstHurt', sa.Float(), nullable=False),
    sa.Column('winAfterOpeningKill', sa.Float(), nullable=False),
    sa.Column('firstSuccessRate', sa.Float(), nullable=False),
    sa.Column('firstKill', sa.Float(), nullable=False),
    sa.Column('firstRate', sa.Float(), nullable=False),
    sa.Column('itemScore', sa.Integer(), nullable=False),
    sa.Column('itemRate', sa.Float(), nullable=False),
    sa.Column('utilityDamagePerRounds', sa.Float(), nullable=False),
    sa.Column('flashAssistPerRound', sa.Float(), nullable=False),
    sa.Column('flashbangFlashRate', sa.Float(), nullable=False),
    sa.Column('timeOpponentFlashedPerRound', sa.Float(), nullable=False),
    sa.Column('oneVnScore', sa.Integer(), nullable=False),
    sa.Column('v1WinPercentage', sa.Float(), nullable=False),
    sa.Column('clutchPointsPerRound', sa.Float(), nullable=False),
    sa.Column('lastAlivePercentage', sa.Float(), nullable=False),
    sa.Column('timeAlivePerRound', sa.Float(), nullable=False),
    sa.Column('savesPerRoundLoss', sa.Float(), nullable=False),
    sa.Column('sniperScore', sa.Integer(), nullable=False),
    sa.Column('sniperFirstKillPercentage', sa.Float(), nullable=False),
    sa.Column('sniperKillsPercentage', sa.Float(), nullable=False),
    sa.Column('sniperKillPerRound', sa.Float(), nullable=False),
    sa.Column('roundsWithSniperKillsPercentage', sa.Float(), nullable=False),
    sa.Column('sniperMultipleKillRoundPercentage', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('steamid', 'seasonId')
    )
    op.create_table('steam_extra_info',
    sa.Column('steamid', sa.String(length=20), nullable=False),
    sa.Column('timeStamp', sa.Integer(), nullable=False),
    sa.Column('legacyScore', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('steamid', 'timeStamp')
    )
    op.create_table('steamid_baseinfo_v2',
    sa.Column('steamid', sa.String(length=20), nullable=False),
    sa.Column('updateTime', sa.Integer(), nullable=False),
    sa.Column('updateMatchTime', sa.Integer(), nullable=False),
    sa.Column('avatarlink', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ladderScore', sa.Text(), nullable=False),
    sa.Column('lasttime', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('steamid')
    )
    op.create_table('user_info',
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('last_send_time', sa.Integer(), nullable=False),
    sa.Column('last_update_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_play_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('steamid', sa.String(length=20), nullable=False),
    sa.Column('timeStamp', sa.Integer(), nullable=False),
    sa.Column('isFirst', sa.Boolean(), nullable=False),
    sa.Column('gameId', sa.Integer(), nullable=False),
    sa.Column('gameName', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', 'steamid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_play_status')
    op.drop_table('user_info')
    op.drop_table('steamid_baseinfo_v2')
    op.drop_table('steam_extra_info')
    op.drop_table('steam_detail_info')
    op.drop_table('members_steamid')
    op.drop_table('member_goods')
    op.drop_table('matches_gp_extra')
    op.drop_table('matches_gp')
    op.drop_table('matches_extra')
    op.drop_table('matches')
    op.drop_table('major_hw')
    op.drop_table('local_storage')
    op.drop_table('live_status')
    op.drop_table('img_cache_info')
    op.drop_table('groupmsg')
    op.drop_table('group_members')
    op.drop_table('goods_info')
    op.drop_table('fudu_points')
    op.drop_index(op.f('ix_auth_sessions_code'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_table('ai_mem')
    # ### end Alembic commands ###
