"""empty message

Revision ID: c21df6155654
Revises: 2708b787750d
Create Date: 2026-02-23 14:26:31.643811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c21df6155654'
down_revision: Union[str, Sequence[str], None] = '2708b787750d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fudu_points', sa.Column('pointType', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fudu_points', 'pointType')
    # ### end Alembic commands ###
