"""empty message

Revision ID: de501b7cf01e
Revises: a13f11ab1c0e
Create Date: 2026-01-09 00:24:23.722280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de501b7cf01e'
down_revision: Union[str, Sequence[str], None] = 'a13f11ab1c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches_gp_extra', sa.Column('updateTime', sa.Integer(), nullable=False))
    op.add_column('matches_gp_extra', sa.Column('fetchCount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches_gp_extra', 'fetchCount')
    op.drop_column('matches_gp_extra', 'updateTime')
    # ### end Alembic commands ###
