"""empty message

Revision ID: fbb4c127e88e
Revises: 50cc623064f9
Create Date: 2026-01-10 11:33:28.539708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbb4c127e88e'
down_revision: Union[str, Sequence[str], None] = '50cc623064f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_play_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('steamid', sa.String(length=20), nullable=False),
    sa.Column('timeStamp', sa.Integer(), nullable=False),
    sa.Column('isFirst', sa.Boolean(), nullable=False),
    sa.Column('gameId', sa.Integer(), nullable=False),
    sa.Column('gameName', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', 'steamid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_play_status')
    # ### end Alembic commands ###
